# Generated by Django 5.0 on 2023-12-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_duration_in_days_subscription_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='description',
        ),
        migrations.AddField(
            model_name='subscription',
            name='benefits',
            field=models.ManyToManyField(to='subscription.benefit'),
        ),
    ]
