# Generated by Django 5.0 on 2023-12-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
