# Generated by Django 5.0 on 2023-12-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subscription_required',
            field=models.BooleanField(default=False),
        ),
    ]
