# Generated by Django 5.0 on 2023-12-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_subscription_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration in minutes'),
        ),
    ]
